server:
  port: 9999

spring:
  rabbitmq:
    host: 192.168.0.111
    port: 5672
    username: pig
    password: lengleng
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    pig-auth:
      path: /auth/**
      serviceId: pig-auth
      stripPrefix: true
      sensitiveHeaders:
    pig-upms-service:
      path: /admin/**
      serviceId: pig-upms-service
      stripPrefix: true
      sensitiveHeaders:
  ratelimit:
    key-prefix: pig-ratelimite 
    enabled: true 
    repository: REDIS 
    behind-proxy: true
    policies:
      pig-upms-service:
        limit: 100
        quota: 100
        refresh-interval: 3

urls:
  anon:
    - /mobile/**
    - /auth/**
    - /admin/code/*
    - /admin/smsCode/*
    - /admin/user/info
    - /admin/menu/userTree
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**
       
logging:
  config: classpath:logback.xml
